services:
  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    container_name: express_server
    ports:
      - "8000:8000"
    env_file:
      - Server/.env
    networks:
      - lumon-network

  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    container_name: react_client
    ports:
      - "5173:5173"
    depends_on:
      - server
    environment:
      VITE_BASE_URL: http://server:8000/api/v1
    env_file:
      - Client/.env
    networks:
      - lumon-network

networks:
  lumon-network:
    driver: bridge
